version: 2

jobs:
  lint:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - checkout
      - run:
          name: Install golangci-lint v1.15
          command: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.15.0
      - run:
          name: Linters
          command: make lint

  test:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - checkout
      - run:
          name: Unit tests
          command: make test

  publish:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/sylabs/slurm-operator
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build and push
          command: make push


workflows:
  version: 2
  build_test_publish:
    jobs:
      - lint
      - test
      - publish:
          requires:
            - lint
            - test
