apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: wlmjobs.wlm.sylabs.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.status
    description: status of the kind
    name: Status
    type: string
  group: wlm.sylabs.io
  names:
    kind: WlmJob
    plural: wlmjobs
    shortNames:
    - wj
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              description: Image name to start as a job.
              type: string
            nodeSelector:
              description: 'NodeSelector is a selector which must be true for the
                WlmJob to fit on a node. Selector which must match a node''s labels
                for the WlmJob to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/.'
              type: object
            resources:
              description: Resources describes required resources for a job.
              properties:
                cpuPerNode:
                  format: int64
                  type: integer
                memPerNode:
                  format: int64
                  type: integer
                nodes:
                  format: int64
                  type: integer
                wallTime:
                  description: WallTime in seconds.
                  format: int64
                  type: integer
              type: object
            results:
              description: Results may be specified for an optional results collection
                step. When specified, after job is completed all results will be downloaded
                from WLM cluster with respect to this configuration.
              properties:
                from:
                  description: From is a path to the results to be collected from
                    a Slurm cluster.
                  type: string
                mount:
                  description: Mount is a directory where job results will be stored.
                    After results collection all job generated files can be found
                    in Mount/<SlurmJob.Name> directory.
                  type: object
              required:
              - mount
              - from
              type: object
          required:
          - image
          type: object
        status:
          properties:
            status:
              description: Status reflects job status, e.g running, succeeded.
              type: string
          required:
          - status
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
