apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: wlmjobs.wlm.sylabs.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.status
    description: status of the kind
    name: Status
    type: string
  group: wlm.sylabs.io
  names:
    kind: WlmJob
    plural: wlmjobs
    shortNames:
    - wj
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            image:
              type: string
            resources:
              properties:
                cpuPerNode:
                  format: int64
                  type: integer
                memPerNode:
                  format: int64
                  type: integer
                nodes:
                  format: int64
                  type: integer
                wallTime:
                  format: int64
                  type: integer
              required:
              - nodes
              - cpuPerNode
              - memPerNode
              - wallTime
              type: object
          required:
          - image
          - resources
          type: object
        status:
          properties:
            status:
              description: Status reflects job status, e.g running, succeeded.
              type: string
          required:
          - status
          type: object
  version: v1alpha1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
