apiVersion: apps/v1
kind: Deployment
metadata:
  name: wlm-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: wlm-operator
  template:
    metadata:
      labels:
        name: wlm-operator
    spec:
      serviceAccountName: wlm-operator
      containers:
        - name: wlm-operator
          image: cloud.sylabs.io/library/slurm/operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "wlm-operator"
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
